name: CI
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "VulkanSDK"
        key: VulkanSDK-1.3.204.1-Installer
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.3.204.1/windows/VulkanSDK-1.3.204.1-Installer.exe -OutFile VulkanSDK-1.3.204.1-Installer.exe
        7z x -aoa ./VulkanSDK-1.3.204.1-Installer.exe -oVulkanSDK 
    - name: build
      run: |
        $env:VULKAN_SDK="$(pwd)/VulkanSDK"
        mkdir build; cd build
        cmake -A x64 ../src
        cmake --build . --config Release -j 2 
        cd ..
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: CainWind
        path: build/Release/cain-ncnn-vulkan.exe
  ubuntu:
    runs-on: ubuntu-18.04
    env:
      PACKAGENAME: cain-ubuntu
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.3.204.1"
        key: vulkansdk-linux-x86_64-1.3.204.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.3.204.1/linux/vulkansdk-linux-x86_64-1.3.204.1.tar.gz
        tar -xf vulkansdk-linux-x86_64-1.3.204.1.tar.gz
        rm -rf 1.3.204.1/source 1.3.204.1/samples
        find 1.3.204.1 -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: build
      run: |
        export VULKAN_SDK=`pwd`/1.3.204.1/x86_64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 4
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: CainLin
        path: build/cain-ncnn-vulkan

